name: Docker Build and Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    # Also publish `debug` for non-release debug images.
    branches:
      - master
      - debug
      - test-ci

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        
      - name: Build image
        run: docker build . --file Dockerfile --tag ggstream
      
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/ggstream
          tag_with_ref: true
          tag_with_sha: false
          cache_froms: ggstream
          push: true
          
      - name: Push to ACR
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_TOKEN }}
          registry: ggstream.azurecr.io
          repository: ggstream
          tag_with_ref: true
          tag_with_sha: true
          cache_froms: ggstream
          push: true

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/test-ci'
    
    steps:
      - name: Update on Cobalt
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: ${{ secrets.UPDATE_CMD }}
